packages:
  - packages/*

nodeLinker: hoisted
symlink: false
preferSymlinkedExecutables: false
storeDir: .pnpm-store

allowBuilds:
  esbuild: true

engineStrict: true
pmOnFail: error
verifyDepsBeforeRun: error
